### ISSUE TITLE
How to get started with Nereond?

### ISSUE THREAD

**Issue by strogonoff** [riboseinc/nereond#10]
How would one go about using Nereon daemon to configure, e.g., an Nginx server to run at system startup? If that’s not a supported use case, then what is?

**Comment by ronaldtse** [comment]
It is an intended use case. To do so, someone would need to write a nereon-nginx adapter. And we don’t have that yet :wink:

**Comment by strogonoff** [comment]
What is a currently supported use case one can get started with right now (after installing nereond)?

**Comment by ronaldtse** [comment]
I believe this example: https://github.com/riboseinc/riffol/tree/master/examples/openvpn

Is to have Nereond write out configuration files intended for OpenVPN. Nereond is still under early development so there's not much to see yet?

cc @drystone

**Comment by drystone** [comment]
Probably best to leave Nereond for now. The existing implementation is simply a placeholder. It doesn't even run as a daemon yet, pending a user interface (Gyndol) which is a little way off.

**Comment by strogonoff** [comment]
I’ll close this and remove the daemon from featured software on Nereon’s site for now
